api_version: 1
runtime: python27
threadsafe: true

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'anyvalue'

libraries:
- name: ssl 
  version: latest

handlers:
- url: .*
  script: groupkit.main.app
  secure: always

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?run_tests.py
- ^.*.example
- bower_components
- env
- frontend
- htmlcov
- lib/Crypto
- lib/PIL
- node_modules
- testing
